name: Run Vitest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project (if needed)
        run: npm run build || echo "No build step"

      - name: Start app in background
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 5

      - name: Run Vitest
        run: npm test
